- Master/o365collector.js
- O365WebHook/ingest_proto.js
- local_dev/o365webhook_local_dev.js
Fill log batches with real metadata:
host_type - azure_fun
local_hostnane - website hostname
P.S. Sorry for the local branch. I'll use private fork next time.
@tomdos @ikemsley @alexturkin
> Fix log batch metadata

- Master/o365collector.js
- package.json
- test/master_test.js
- test/mock.js
Webhook address was not updated if web app is reinstalled with the same app identity
Check webhook address is correct during checkin and overwrite it if necessary.
@tomdos @ikemsley @alexturkin @andrey-smirnov
> Webhook validation

- README.md
- template.json
Deployment and function invocation performance is very low.
Use [funpack option](https://github.com/projectkudu/kudu/wiki/Configurable-settings#automatically-run-funcpack-on-function-app-git-deployments) to speed up cold start and function invocations.
@tomdos @ikemsley @alexturkin @andrey-smirnov
> Funpack setting

- Master/index.js
- Updater/index.js
Function invocations returned OK even in case of errors.
Return errors into `context.done()`
@alexturkin @ikemsley @tomdos @andrey-smirnov
> Return errors into context.done()

- README.md
- template.json
**Problem**
User has to assign Web Site Contributor role to Web App manually
**Solution**
Assign Contributor built-in RBAC role via ARM template and `Service Principal ID` provided by user.
> US63918 - Create RBAC role for app identity via ARM template

- PostDeploymentActions/updateMasterTimer.ps1
- PostDeploymentActions/updateUpdaterTimer.ps1
- template.json
All functions are executed at the same time if same cron expression is used. This lead to a spikey usage pattern of Alertlogic web services and Github during checkins and Updates.
Add post deployment webhooks to distribute checkins and updates over time.
This change also fixes the delay with the collector registration. Previously the first master invocation happened 15 mins after a deployment was successful. Now master function should be invoked within 1 min after the Web app deployment.
@ikemsley @tomdos @alexturkin @andrey-smirnov
> Checkins and updates time distribution

- Master/endpoints.js
- Master/index.js
- Master/o365collector.js
- O365WebHook/index.js
- O365WebHook/ingest_proto.js
- O365WebHook/o365content.js
- Updater/index.js
- local_dev/master_local_dev.js
- local_dev/o365webhook_local_dev.js
- local_dev/updater_local_dev.js
- test/mock.js
Use Azure fun build-in log levels for logging.
https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference-node#writing-trace-output-to-the-console
@tomdos @ikemsley @andrey-smirnov @alexturkin
> Use built-in azure fun log levels.

- O365WebHook/index.js
- Updater/index.js
- package.json
Explicitly fail function invocation in case of failures.
@tomdos @ikemsley @andrey-smirnov @alexturkin
> Return errors in Updater and Webhook

- package.json
version 1.0.2
@kkuzmin @ikemsley
> Integration

- package.json
Reverts alertlogic/azure-collector#18
> Revert "Release 1.0.4"

- README.md
Providing bash commands for getting AL keys.
@ikemsley @andrey-smirnov @tomdos @alexturkin
> Amend creation of AL key section.

- README.md
Readme updates.
Package version hasn't been changed.
@tomdos @ikemsley @alexturkin @andrey-smirnov
> Readme updates. Amend creation of AL key section.

- README.md
Check if AL user has Administrator role before creating access keys.
@tomdos @ikemsley @nalundgaard
> Check is AL user has administrator role.

- README.md
- package.json
FYI @tomdos @andrey-smirnov @ikemsley
> Readme Updates

- lib/o365_mgmnt/o365management.js
Fix typos in O365 `content/list` and `notifications/list`
@tomdos @ikemsley @alexturkin
> Fix typos.

- lib/o365_mgmnt/index.js
- package.json
Make O365 management library logs more verbose.
@tomdos @andrey-smirnov @alexturkin
> Add more verbose logging.

- Master/index.js
Add old names for source ID and Host ID to Master function
> Add old config vars to checkin

- package.json
* Readme updates from integration (#49)
* Readme Updates
* additional minor updates per feedback
* Update README.md (#47)
* Update README.md
Info Dev edits applied to Integration branch.
* Removed comments; Removed DLP.All list.
* hard pin library deps
* update al-collector-js dep
> O365 Collector release 1.2.0 (#60)

- package.json
This changes the encoding that the collector uses to send to ingest
> Direct mode

- lib/o365_mgmnt/index.js
- lib/o365_mgmnt/o365management.js
- package.json
We need to migrate away from the deprecated azure sdks. This addresses that issue
> Change to newer sdks

- lib/o365_mgmnt/index.js
- lib/o365_mgmnt/o365management.js
- package.json
* change to newest sdks
* clean up index file
* add the environment back in
* change to odl-new sdks
> Change to newer sdks (#69)

- .deployment
- deploy.cmd
- lib/o365_mgmnt/index.js
- lib/o365_mgmnt/o365management.js
- local_dev/master_local_dev.js
- local_dev/o365webhook_local_dev.js
- local_dev/updater_local_dev.js
- package.json
*  update to newest sdks
* change version and add test dep
* add custom build scripts
* change token audience
* refecctor to sue promises
* fix up request handler
* change execution context for local dev
* remove some errant console.logs
* update dep in package.json
* remove uneccessary console.log
> Sdk newest versions (#72)

- README.md
- template.json
deploy pulls template from master, the most recent template changes only in integration branch
> storage account name changes, update readme

- README.md
- template.json
param fix for storage account name generation
> propagate changes to master

- template.json
missed a paren in the last commit, leading to a breaking template change
> missing paren, breaking template

- README.md
Duplicated the information from
https://docs.alertlogic.com/prepare/office365-log-collector.htm
> README: add link to new (PAWS) collector set up instructions

- .travis.yml
- package.json
- template.json
Node update is required as the current is EOL.
Updated node to version 12.
> Changes for node 12 update

- .travis.yml
- ps_spec.yml
> Change CI build to ALPS
